/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/agents': RouteRecordInfo<
      '/agents',
      '/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/conversions/[id]': RouteRecordInfo<
      '/conversions/[id]',
      '/conversions/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/inbox': RouteRecordInfo<
      '/inbox',
      '/inbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/[id]': RouteRecordInfo<
      '/projects/[id]',
      '/projects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/projects/[id]/settings'
      | '/projects/[id]/worktrees'
    >,
    '/projects/[id]/settings': RouteRecordInfo<
      '/projects/[id]/settings',
      '/projects/:id/settings',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/worktrees': RouteRecordInfo<
      '/projects/[id]/worktrees',
      '/projects/:id/worktrees',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/rules': RouteRecordInfo<
      '/rules',
      '/rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/agents.vue': {
      routes:
        | '/agents'
      views:
        | never
    }
    'src/pages/conversions/[id].vue': {
      routes:
        | '/conversions/[id]'
      views:
        | never
    }
    'src/pages/inbox.vue': {
      routes:
        | '/inbox'
      views:
        | never
    }
    'src/pages/projects/[id].vue': {
      routes:
        | '/projects/[id]'
        | '/projects/[id]/settings'
        | '/projects/[id]/worktrees'
      views:
        | 'default'
    }
    'src/pages/projects/[id]/settings.vue': {
      routes:
        | '/projects/[id]/settings'
      views:
        | never
    }
    'src/pages/projects/[id]/worktrees.vue': {
      routes:
        | '/projects/[id]/worktrees'
      views:
        | never
    }
    'src/pages/rules.vue': {
      routes:
        | '/rules'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
